### ISSUE TITLE
git --list-cmds proper usage

### ISSUE THREAD

**Issue by DaniilPalii** [rehnarama/pwsh-git-completion#5]
https://github.com/rehnarama/pwsh-git-completion/blob/1b4d4a83acce93491252b7d6a5cb32353526d6ac/pwsh-git-completion.psm1#L37C35-L37C35

The command `git --list-cmds=main, others, alias, nohelpers` returns only main commands because `git --list-cmds` does not supports spaces. It shoud be changed to `git --list-cmds=main,others,alias,nohelpers`. Maybe the behavior of the command was changed, since it is experimental command.

Documentation - https://git-scm.com/docs/git#Documentation/git.txt---list-cmdsgroupgroup82308203

**Comment by DaniilPalii** [comment]
I will try to create pull request this week.

Anyway, great work, @rehnarama. The completer is really fast and functional. Thank you!

**Comment by DaniilPalii** [comment]
PR: https://github.com/rehnarama/pwsh-git-completion/pull/6

**Comment by rehnarama** [comment]
Thanks for the PR @DaniilPalii, I'll get it merge and re-publish a new version this weekend.

**Comment by rehnarama** [comment]
@DaniilPalii Release to powershell gallery now as version 0.0.5, thanks! https://www.powershellgallery.com/packages/pwsh-git-completion/0.0.5
